# Generated by Django 4.2.7 on 2023-11-16 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_article_pub_date_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 11, 59, 51, 871446, tzinfo=datetime.timezone.utc)),
        ),
    ]
