# Generated by Django 4.2.7 on 2023-11-30 09:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_article_pub_date_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
