# Generated by Django 4.2.7 on 2023-11-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_article_managers_article_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
    ]
